# Generated by Django 4.2 on 2024-12-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notification',
        ),
    ]
