# Generated by Django 4.2 on 2024-12-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_customuser_antecedents_medicaux_customuser_poids_and_more'),
        ('patient', '0018_customuser_face_embeddings_customuser_face_image'),
    ]

    operations = [
    ]
