# Generated by Django 4.2 on 2024-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_merge_20241215_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
