# Generated by Django 4.2 on 2024-12-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_merge_20241215_1908'),
        ('patient', '0020_alter_customuser_face_image'),
    ]

    operations = [
    ]
